Add feature that save graph image
fosslight/fosslight_dependency_scanner pull request #214
Opened 2024-07-30 11:21 UTC by fhdufhdu

## Description

Add feature that save graph image
Using `igraph-python` Opensoure Libraray
 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-07-31 01:35 UTC, soimkim commented
@fhdufhdu , tox -e release 에러 확인 부탁드립니다.
requirements.txt에 igraph 추가가 필요합니다.

2024-08-01 02:06 UTC, fhdufhdu commented
> @fhdufhdu , tox -e release 에러 확인 부탁드립니다. requirements.txt에 igraph 추가가 필요합니다.

수정했습니다. 확인 부탁드릴께요!

2024-08-01 04:34 UTC, soimkim commented on src/fosslight_dependency/run_dependency_scanner.py
> +                           path_to_exclude=[]):
graph_path='', graph_size=(600, 600)는 나중에 추가된 parameter이므로 맨 끝으로 이동해주십시오.

2024-08-02 01:49 UTC, soimkim commented on src/fosslight_dependency/run_dependency_scanner.py
> +                           path_to_exclude=[]):
수정 완료된 사항은 Resolve conversation 부탁드립니다. 😃

2024-08-03 04:36 UTC, soimkim commented
분석 실패 했을 경우에 대한 예외처리가 필요합니다. 

테스트 방법:
```
$ sudo npm uninstall -g license-checker 한 후 
$ fosslight_dependency -p tests/test_npm1 --graph-path .

It returns the error: license-checker --production --json --out tmp_npm_license_output.json --customPath custom.json
Please check if the license-checker is installed.(sudo npm install -g license-checker)
### Fail to analyze: npm
Traceback (most recent call last):
  File "/Users/soim/mambaforge/bin/fosslight_dependency", line 8, in <module>
    sys.exit(main())
  File "/Users/soim/mambaforge/lib/python3.10/site-packages/fosslight_dependency/run_dependency_scanner.py", line 359, in main
    run_dependency_scanner(package_manager, input_dir, output_dir, pip_activate_cmd, pip_deactivate_cmd,
  File "/Users/soim/mambaforge/lib/python3.10/site-packages/fosslight_dependency/run_dependency_scanner.py", line 240, in run_dependency_scanner
    converter.save(graph_path, graph_size)
  File "/Users/soim/mambaforge/lib/python3.10/site-packages/fosslight_dependency/_graph_convertor.py", line 53, in save
    ig.plot(
  File "/Users/soim/mambaforge/lib/python3.10/site-packages/igraph/drawing/__init__.py", line 267, in plot
    result = plotter(
  File "/Users/soim/mambaforge/lib/python3.10/site-packages/igraph/drawing/graph.py", line 561, in __plot__
    return drawer.draw(self, *args, **kwds)
  File "/Users/soim/mambaforge/lib/python3.10/site-packages/igraph/drawing/matplotlib/graph.py", line 811, in draw
    art = GraphArtist(
  File "/Users/soim/mambaforge/lib/python3.10/site-packages/igraph/drawing/matplotlib/graph.py", line 166, in __init__
    self._kwds_post_update()
  File "/Users/soim/mambaforge/lib/python3.10/site-packages/igraph/drawing/matplotlib/graph.py", line 169, in _kwds_post_update
    self.kwds["layout"] = self.ensure_layout(self.kwds["layout"], self.graph)
  File "/Users/soim/mambaforge/lib/python3.10/site-packages/igraph/drawing/baseclasses.py", line 297, in ensure_layout
    layout = graph.layout(layout)
  File "/Users/soim/mambaforge/lib/python3.10/site-packages/igraph/layout.py", line 531, in _layout
    layout = method(graph, *args, **kwds)
  File "/Users/soim/mambaforge/lib/python3.10/site-packages/igraph/layout.py", line 691, in result
    layout = func(*args, **kwds)
ValueError: number of iterations must be positive
```

2024-08-03 04:44 UTC, soimkim commented
Improvement
-  파일 생성 완료시, 하기 로그의 result_file에 생성된 이미지 파일도 추가 부탁드립니다. 
`logger.info(f"Output file: {result_file}")`

2024-08-03 04:52 UTC, soimkim requested changes

2024-08-03 04:52 UTC, soimkim commented on requirements.txt
> +matplotlib==3.7.5
matplotlib 의 버전 fix하지 말아주십시오.
다른 Scanner와 함께 설치지시 버전 충돌이 일어납니다. 
      
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
matplotlib 3.7.5 requires numpy<2,>=1.20, but you have numpy 2.0.1 which is incompatible.
```

2024-08-03 04:53 UTC, soimkim commented on requirements.txt
> +matplotlib==3.7.5
igraph도 버전 fix 필요한 사항이 아니라면 하지 않는 것을 제안드립니다.

2024-08-03 06:51 UTC, soimkim commented on src/fosslight_dependency/_help.py
> +            --graph_size <width> <height>   Enter the size of the graph image (The size unit is pixels)
--graph_size  -> --graph-size 
 --graph_path ->  --graph-path

2024-08-03 07:01 UTC, soimkim commented
@fhdufhdu , 가이드의 help message 업데이트, 결과 파일에 graph image file 예시 추가 부탁드립니다. : https://fosslight.org/fosslight-guide-en/scanner/3_dependency.html
- 영어 : https://github.com/fosslight/fosslight-guide-en
- 한글 : https://github.com/fosslight/fosslight-guide

2024-08-03 07:03 UTC, merged